#include "sortAlgorithms/bubbleSort.h"
#include "sortAlgorithms/selectionSort.h"
#include "sortAlgorithms/insertionSort.h"
#include "sortAlgorithms/mergeSort.h"
#include "sortAlgorithms/heapSort.h"
#include "sortAlgorithms/quickSort.h"
#include "sortAlgorithms/countingSort.h"